INSERT INTO `wspolnoty`.`wspolnota` ( `adres_wspolnoty`,`budynek`,`nazwa_wspolnoty`) VALUES( "Kwiska 24","33-40","Gondow");
INSERT INTO `wspolnoty`.`wspolnota` (`adres_wspolnoty`,`budynek`,`nazwa_wspolnoty`) VALUES("Kamienna 5","1-12","Krzyki");
INSERT INTO `wspolnoty`.`wspolnota` (`adres_wspolnoty`,`budynek`,`nazwa_wspolnoty`) VALUES("Drobnera","21-31","Centrum");
INSERT INTO `wspolnoty`.`wspolnota` (`adres_wspolnoty`,`budynek`,`nazwa_wspolnoty`) VALUES("Baltycka","1-3","Psie Pole");
INSERT INTO `wspolnoty`.`mieszkanie` ( `numer_mieszkania`,`powierzchnia_mieszkania`,`ulica`,`wspolnota_id_wspolnoty`) VALUES ("23/1", 150, "Kwiska", 1);
INSERT INTO `wspolnoty`.`mieszkanie` (`numer_mieszkania`,`powierzchnia_mieszkania`,`ulica`,`wspolnota_id_wspolnoty`) VALUES ("23/2", 80, "Kwiska", 1);
INSERT INTO `wspolnoty`.`mieszkanie` (`numer_mieszkania`,`powierzchnia_mieszkania`,`ulica`,`wspolnota_id_wspolnoty`) VALUES ("25/3", 200, "Kwiska", 1);
INSERT INTO `wspolnoty`.`mieszkanie` (`numer_mieszkania`,`powierzchnia_mieszkania`,`ulica`,`wspolnota_id_wspolnoty`) VALUES ("3/1", 150, "Drukarska", 3);
INSERT INTO `wspolnoty`.`mieszkanie` (`numer_mieszkania`,`powierzchnia_mieszkania`,`ulica`,`wspolnota_id_wspolnoty`) VALUES ("3/2", 150, "Drukarska", 3);
INSERT INTO `wspolnoty`.`mieszkanie` (`numer_mieszkania`,`powierzchnia_mieszkania`,`ulica`,`wspolnota_id_wspolnoty`) VALUES ("22/1", 90, "Bałtycka", 4);
INSERT INTO `wspolnoty`.`mieszkanie` (`numer_mieszkania`,`powierzchnia_mieszkania`,`ulica`,`wspolnota_id_wspolnoty`) VALUES ("22/6", 90, "Bałtycka", 4);
INSERT INTO `wspolnoty`.`osoba` (`imie`,`nazwisko`,`plec`,`mieszkanie_id_mieszkania`) VALUES ( "Anna", "Nowak", "KOBIETA", 1);
INSERT INTO `wspolnoty`.`osoba` (`imie`,`nazwisko`,`plec`,`mieszkanie_id_mieszkania`) VALUES ( "Piotr", "Nowak", "MEZCZYZNA", 1);
INSERT INTO `wspolnoty`.`osoba` (`imie`,`nazwisko`,`plec`,`mieszkanie_id_mieszkania`) VALUES ( "Magdalena", "Kowal",  "KOBIETA", 2);
INSERT INTO `wspolnoty`.`osoba` (`imie`,`nazwisko`,`plec`,`mieszkanie_id_mieszkania`) VALUES ( "Marcin", "Kowal", "MEZCZYZNA", 2);
INSERT INTO `wspolnoty`.`osoba` (`imie`,`nazwisko`,`plec`,`mieszkanie_id_mieszkania`) VALUES ( "Jaś", "Kowal", "MEZCZYZNA", 2);
INSERT INTO `wspolnoty`.`osoba` (`imie`,`nazwisko`,`plec`,`mieszkanie_id_mieszkania`) VALUES ("Genowefa", "Polak",  "KOBIETA", 3);
INSERT INTO `wspolnoty`.`osoba` (`imie`,`nazwisko`,`plec`,`mieszkanie_id_mieszkania`) VALUES ( "Robert", "Nowak", "MEZCZYZNA", 4);
INSERT INTO `wspolnoty`.`osoba` (`imie`,`nazwisko`,`plec`,`mieszkanie_id_mieszkania`) VALUES ("Anna", "Zawada", "KOBIETA", 5);
INSERT INTO `wspolnoty`.`osoba` (`imie`,`nazwisko`,`plec`,`mieszkanie_id_mieszkania`) VALUES ("Paweł", "Zawada", "MEZCZYZNA",5);